import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import type { ResourceIndex, ResourceItem } from '../../shared/types/resources';
import type { Diagnostic } from '../../shared/types/elements';

async function sha256(file: string): Promise<string> {
  const data = await fs.readFile(file);
  return crypto.createHash('sha256').update(data).digest('hex');
}

function sha256Buffer(data: Buffer): string {
  return crypto.createHash('sha256').update(data).digest('hex');
}

function textureKind(usage: 'item_texture' | 'block_texture'): 'item' | 'block' {
  return usage === 'item_texture' ? 'item' : 'block';
}

function textureIdFromOwner(ownerElement: string): string {
  return ownerElement.split(':')[1] || ownerElement;
}

function validateTextureName(name: string): string {
  const value = name.trim();
  if (!/^[a-z0-9_]+$/.test(value)) {
    throw new Error('贴图名只能使用小写英文字母、数字和下划线，例如 ice_wand 或 frost_block。');
  }
  return value;
}

function parsePngDimensions(data: Buffer): { width: number; height: number } {
  const signature = '89504e470d0a1a0a';
  if (data.length < 24 || data.subarray(0, 8).toString('hex') !== signature) {
    throw new Error('贴图必须是 PNG 文件。');
  }
  const width = data.readUInt32BE(16);
  const height = data.readUInt32BE(20);
  return { width, height };
}

function validateTexturePng(data: Buffer): { width: number; height: number } {
  const dimensions = parsePngDimensions(data);
  if (dimensions.width !== dimensions.height) {
    throw new Error(`贴图必须是正方形 PNG，当前尺寸为 ${dimensions.width}x${dimensions.height}。`);
  }
  if (![16, 32, 64].includes(dimensions.width)) {
    throw new Error(`贴图尺寸只能是 16x16、32x32 或 64x64，当前尺寸为 ${dimensions.width}x${dimensions.height}。`);
  }
  return dimensions;
}

function decodePngDataUrl(dataUrl: string): Buffer {
  const match = dataUrl.match(/^data:image\/png;base64,([A-Za-z0-9+/=]+)$/);
  if (!match) throw new Error('绘制结果必须是 PNG data URL。');
  return Buffer.from(match[1], 'base64');
}

export async function readResourceIndex(projectDir: string): Promise<ResourceIndex> {
  const file = path.join(projectDir, 'editor/resources/index.json');
  try { return JSON.parse(await fs.readFile(file, 'utf8')) as ResourceIndex; }
  catch { return { schemaVersion: '0.1.0', resources: [] }; }
}

export async function writeResourceIndex(projectDir: string, index: ResourceIndex): Promise<void> {
  const file = path.join(projectDir, 'editor/resources/index.json');
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, JSON.stringify(index, null, 2), 'utf8');
}

export async function importTexture(projectDir: string, sourceFile: string, usage: 'item_texture' | 'block_texture', ownerElement: string, modId: string): Promise<ResourceItem> {
  const kind = textureKind(usage);
  const id = validateTextureName(textureIdFromOwner(ownerElement) || path.basename(sourceFile, path.extname(sourceFile)));
  const data = await fs.readFile(sourceFile);
  validateTexturePng(data);
  const dest = path.join(projectDir, 'editor/resources/textures', kind, `${id}.png`);
  await fs.mkdir(path.dirname(dest), { recursive: true });
  await fs.writeFile(dest, data);
  const resource: ResourceItem = {
    resourceId: `texture_${kind}_${id}`,
    path: path.relative(projectDir, dest).replace(/\\/g, '/'),
    generatedPath: `generated/forge/src/main/resources/assets/${modId}/textures/${kind}/${id}.png`,
    type: 'texture',
    usage,
    ownerElement,
    referencedBy: [ownerElement],
    hash: await sha256(dest),
    missing: false,
    unused: false,
    autoGenerated: false,
    userImported: true,
    advancedCodeReferenced: false,
    updatedAt: new Date().toISOString()
  };
  const index = await readResourceIndex(projectDir);
  index.resources = index.resources.filter(r => r.resourceId !== resource.resourceId).concat(resource);
  await writeResourceIndex(projectDir, index);
  return resource;
}

export async function saveTextureDataUrl(
  projectDir: string,
  pngDataUrl: string,
  usage: 'item_texture' | 'block_texture',
  ownerElement: string,
  modId: string,
  textureName?: string
): Promise<ResourceItem> {
  const kind = textureKind(usage);
  const id = validateTextureName(textureName || textureIdFromOwner(ownerElement));
  const data = decodePngDataUrl(pngDataUrl);
  validateTexturePng(data);
  const dest = path.join(projectDir, 'editor/resources/textures', kind, `${id}.png`);
  await fs.mkdir(path.dirname(dest), { recursive: true });
  await fs.writeFile(dest, data);
  const resource: ResourceItem = {
    resourceId: `texture_${kind}_${id}`,
    path: path.relative(projectDir, dest).replace(/\\/g, '/'),
    generatedPath: `generated/forge/src/main/resources/assets/${modId}/textures/${kind}/${id}.png`,
    type: 'texture',
    usage,
    ownerElement,
    referencedBy: [ownerElement],
    hash: sha256Buffer(data),
    missing: false,
    unused: false,
    autoGenerated: false,
    userImported: true,
    advancedCodeReferenced: false,
    updatedAt: new Date().toISOString()
  };
  const index = await readResourceIndex(projectDir);
  index.resources = index.resources.filter(r => r.resourceId !== resource.resourceId).concat(resource);
  await writeResourceIndex(projectDir, index);
  return resource;
}

function ensureInsideProject(projectDir: string, relativePath: string): string {
  const root = path.resolve(projectDir);
  const target = path.resolve(projectDir, relativePath);
  if (!target.startsWith(root)) throw new Error('拒绝访问项目目录之外的资源文件。');
  return target;
}

function nextCopyName(existing: Set<string>, baseName: string): string {
  let index = 1;
  let candidate = `${baseName}_copy`;
  while (existing.has(candidate)) {
    index += 1;
    candidate = `${baseName}_copy_${index}`;
  }
  return candidate;
}

export async function duplicateTextureResource(projectDir: string, resourceId: string, modId: string, newName?: string): Promise<ResourceItem> {
  const index = await readResourceIndex(projectDir);
  const sourceResource = index.resources.find(resource => resource.resourceId === resourceId);
  if (!sourceResource) throw new Error(`没有找到资源：${resourceId}`);
  if (sourceResource.type !== 'texture') throw new Error('当前只支持复制贴图资源。');
  const usage = sourceResource.usage === 'block_texture' ? 'block_texture' : 'item_texture';
  const kind = textureKind(usage);
  const existingNames = new Set(index.resources.filter(resource => resource.type === 'texture').map(resource => path.basename(resource.path, '.png')));
  const sourceName = path.basename(sourceResource.path, '.png');
  const id = validateTextureName(newName || nextCopyName(existingNames, sourceName));
  const source = ensureInsideProject(projectDir, sourceResource.path);
  const data = await fs.readFile(source);
  validateTexturePng(data);
  const dest = path.join(projectDir, 'editor/resources/textures', kind, `${id}.png`);
  await fs.mkdir(path.dirname(dest), { recursive: true });
  await fs.writeFile(dest, data);
  const resource: ResourceItem = {
    ...sourceResource,
    resourceId: `texture_${kind}_${id}`,
    path: path.relative(projectDir, dest).replace(/\\/g, '/'),
    generatedPath: `generated/forge/src/main/resources/assets/${modId}/textures/${kind}/${id}.png`,
    hash: sha256Buffer(data),
    missing: false,
    unused: false,
    updatedAt: new Date().toISOString()
  };
  index.resources = index.resources.filter(item => item.resourceId !== resource.resourceId).concat(resource);
  await writeResourceIndex(projectDir, index);
  return resource;
}

export async function deleteResource(projectDir: string, resourceId: string): Promise<ResourceIndex> {
  const index = await readResourceIndex(projectDir);
  const resource = index.resources.find(item => item.resourceId === resourceId);
  if (!resource) return index;
  const target = ensureInsideProject(projectDir, resource.path);
  await fs.rm(target, { force: true });
  index.resources = index.resources.filter(item => item.resourceId !== resourceId);
  await writeResourceIndex(projectDir, index);
  return index;
}

export async function copyResourcesToForge(projectDir: string, modId: string): Promise<ResourceItem[]> {
  const index = await readResourceIndex(projectDir);
  const copied: ResourceItem[] = [];
  for (const resource of index.resources) {
    if (resource.type !== 'texture') continue;
    const source = path.join(projectDir, resource.path);
    const target = path.join(projectDir, 'generated/forge/src/main/resources/assets', modId, 'textures', resource.usage === 'block_texture' ? 'block' : 'item', path.basename(resource.path));
    try {
      await fs.mkdir(path.dirname(target), { recursive: true });
      await fs.copyFile(source, target);
      resource.generatedPath = path.relative(projectDir, target).replace(/\\/g, '/');
      resource.missing = false;
      copied.push(resource);
    } catch {
      resource.missing = true;
    }
  }
  await writeResourceIndex(projectDir, index);
  return copied;
}

export async function checkResources(projectDir: string): Promise<Diagnostic[]> {
  const index = await readResourceIndex(projectDir);
  const diagnostics: Diagnostic[] = [];
  for (const resource of index.resources) {
    try {
      await fs.stat(path.join(projectDir, resource.path));
    } catch {
      diagnostics.push({
        level: 'error',
        code: 'RESOURCE_MISSING',
        message: `资源文件缺失：${resource.path}`,
        target: resource.ownerElement,
        humanAdvice: '请重新导入贴图，或把元素改为使用现有贴图。'
      });
      resource.missing = true;
    }
    if (resource.referencedBy.length === 0) {
      diagnostics.push({
        level: 'warning',
        code: 'RESOURCE_UNUSED',
        message: `资源未被使用：${resource.path}`,
        target: resource.resourceId,
        humanAdvice: '请把它绑定到元素，或从项目资源中移除。'
      });
      resource.unused = true;
    }
  }
  await writeResourceIndex(projectDir, index);
  return diagnostics;
}
