import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import type { ResourceIndex, ResourceItem } from '../../shared/types/resources';
import type { Diagnostic } from '../../shared/types/elements';

async function sha256(file: string): Promise<string> {
  const data = await fs.readFile(file);
  return crypto.createHash('sha256').update(data).digest('hex');
}

function sha256Buffer(data: Buffer): string {
  return crypto.createHash('sha256').update(data).digest('hex');
}

function textureKind(usage: 'item_texture' | 'block_texture'): 'item' | 'block' {
  return usage === 'item_texture' ? 'item' : 'block';
}

function textureIdFromOwner(ownerElement: string): string {
  return ownerElement.split(':')[1] || ownerElement;
}

function modelKind(usage: 'item_model' | 'block_model'): 'item' | 'block' {
  return usage === 'block_model' ? 'block' : 'item';
}

function validateResourceName(name: string, label = '资源'): string {
  const value = name.trim();
  if (!/^[a-z0-9_]+$/.test(value)) {
    throw new Error(`${label}名只能使用小写英文字母、数字和下划线，例如 ice_wand 或 frost_block。`);
  }
  return value;
}

function validateTextureName(name: string): string {
  return validateResourceName(name, '贴图');
}

function validateModelName(name: string): string {
  return validateResourceName(name, '模型');
}

function parsePngDimensions(data: Buffer): { width: number; height: number } {
  const signature = '89504e470d0a1a0a';
  if (data.length < 24 || data.subarray(0, 8).toString('hex') !== signature) {
    throw new Error('贴图必须是 PNG 文件。');
  }
  const width = data.readUInt32BE(16);
  const height = data.readUInt32BE(20);
  return { width, height };
}

function validateTexturePng(data: Buffer): { width: number; height: number } {
  const dimensions = parsePngDimensions(data);
  if (dimensions.width !== dimensions.height) {
    throw new Error(`贴图必须是正方形 PNG，当前尺寸为 ${dimensions.width}x${dimensions.height}。`);
  }
  if (![16, 32, 64].includes(dimensions.width)) {
    throw new Error(`贴图尺寸只能是 16x16、32x32 或 64x64，当前尺寸为 ${dimensions.width}x${dimensions.height}。`);
  }
  return dimensions;
}

function decodePngDataUrl(dataUrl: string): Buffer {
  const match = dataUrl.match(/^data:image\/png;base64,([A-Za-z0-9+/=]+)$/);
  if (!match) throw new Error('绘制结果必须是 PNG data URL。');
  return Buffer.from(match[1], 'base64');
}

function modelResourcePath(projectDir: string, usage: 'item_model' | 'block_model', name: string): string {
  return path.join(projectDir, 'editor/resources/models', modelKind(usage), `${name}.json`);
}

function modelGeneratedPath(modId: string, usage: 'item_model' | 'block_model', name: string): string {
  return `generated/forge/src/main/resources/assets/${modId}/models/${modelKind(usage)}/${name}.json`;
}

function modelResourceId(usage: 'item_model' | 'block_model', name: string): string {
  return `model_${modelKind(usage)}_${name}`;
}

export async function readResourceIndex(projectDir: string): Promise<ResourceIndex> {
  const file = path.join(projectDir, 'editor/resources/index.json');
  try { return JSON.parse(await fs.readFile(file, 'utf8')) as ResourceIndex; }
  catch { return { schemaVersion: '0.1.0', resources: [] }; }
}

export async function writeResourceIndex(projectDir: string, index: ResourceIndex): Promise<void> {
  const file = path.join(projectDir, 'editor/resources/index.json');
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, JSON.stringify(index, null, 2), 'utf8');
}

export async function importTexture(projectDir: string, sourceFile: string, usage: 'item_texture' | 'block_texture', ownerElement: string, modId: string): Promise<ResourceItem> {
  const kind = textureKind(usage);
  const id = validateTextureName(textureIdFromOwner(ownerElement) || path.basename(sourceFile, path.extname(sourceFile)));
  const data = await fs.readFile(sourceFile);
  validateTexturePng(data);
  const dest = path.join(projectDir, 'editor/resources/textures', kind, `${id}.png`);
  await fs.mkdir(path.dirname(dest), { recursive: true });
  await fs.writeFile(dest, data);
  const resource: ResourceItem = {
    resourceId: `texture_${kind}_${id}`,
    path: path.relative(projectDir, dest).replace(/\\/g, '/'),
    generatedPath: `generated/forge/src/main/resources/assets/${modId}/textures/${kind}/${id}.png`,
    type: 'texture',
    usage,
    ownerElement,
    referencedBy: [ownerElement],
    hash: await sha256(dest),
    missing: false,
    unused: false,
    autoGenerated: false,
    userImported: true,
    advancedCodeReferenced: false,
    updatedAt: new Date().toISOString()
  };
  const index = await readResourceIndex(projectDir);
  index.resources = index.resources.filter(r => r.resourceId !== resource.resourceId).concat(resource);
  await writeResourceIndex(projectDir, index);
  return resource;
}

export async function saveTextureDataUrl(
  projectDir: string,
  pngDataUrl: string,
  usage: 'item_texture' | 'block_texture',
  ownerElement: string,
  modId: string,
  textureName?: string
): Promise<ResourceItem> {
  const kind = textureKind(usage);
  const id = validateTextureName(textureName || textureIdFromOwner(ownerElement));
  const data = decodePngDataUrl(pngDataUrl);
  validateTexturePng(data);
  const dest = path.join(projectDir, 'editor/resources/textures', kind, `${id}.png`);
  await fs.mkdir(path.dirname(dest), { recursive: true });
  await fs.writeFile(dest, data);
  const resource: ResourceItem = {
    resourceId: `texture_${kind}_${id}`,
    path: path.relative(projectDir, dest).replace(/\\/g, '/'),
    generatedPath: `generated/forge/src/main/resources/assets/${modId}/textures/${kind}/${id}.png`,
    type: 'texture',
    usage,
    ownerElement,
    referencedBy: [ownerElement],
    hash: sha256Buffer(data),
    missing: false,
    unused: false,
    autoGenerated: false,
    userImported: true,
    advancedCodeReferenced: false,
    updatedAt: new Date().toISOString()
  };
  const index = await readResourceIndex(projectDir);
  index.resources = index.resources.filter(r => r.resourceId !== resource.resourceId).concat(resource);
  await writeResourceIndex(projectDir, index);
  return resource;
}

export async function importModelJson(
  projectDir: string,
  sourceFile: string,
  usage: 'item_model' | 'block_model',
  ownerElement: string,
  modId: string,
  modelName?: string
): Promise<ResourceItem> {
  const raw = await fs.readFile(sourceFile, 'utf8');
  const parsed = JSON.parse(raw);
  return saveModelJson(projectDir, JSON.stringify(parsed, null, 2), usage, ownerElement, modId, modelName || path.basename(sourceFile, path.extname(sourceFile)));
}

export async function saveModelJson(
  projectDir: string,
  jsonText: string,
  usage: 'item_model' | 'block_model',
  ownerElement: string,
  modId: string,
  modelName?: string
): Promise<ResourceItem> {
  const name = validateModelName(modelName || textureIdFromOwner(ownerElement) || 'model');
  const parsed = JSON.parse(jsonText);
  const content = `${JSON.stringify(parsed, null, 2)}\n`;
  const dest = modelResourcePath(projectDir, usage, name);
  await fs.mkdir(path.dirname(dest), { recursive: true });
  await fs.writeFile(dest, content, 'utf8');
  const resource: ResourceItem = {
    resourceId: modelResourceId(usage, name),
    path: path.relative(projectDir, dest).replace(/\\/g, '/'),
    generatedPath: modelGeneratedPath(modId, usage, name),
    type: 'model',
    usage,
    ownerElement: ownerElement || undefined,
    referencedBy: ownerElement ? [ownerElement] : [],
    hash: sha256Buffer(Buffer.from(content, 'utf8')),
    missing: false,
    unused: false,
    autoGenerated: false,
    userImported: true,
    advancedCodeReferenced: false,
    updatedAt: new Date().toISOString()
  };
  const index = await readResourceIndex(projectDir);
  index.resources = index.resources.filter(r => r.resourceId !== resource.resourceId).concat(resource);
  await writeResourceIndex(projectDir, index);
  return resource;
}

function ensureInsideProject(projectDir: string, relativePath: string): string {
  const root = path.resolve(projectDir);
  const target = path.resolve(projectDir, relativePath);
  if (!target.startsWith(root)) throw new Error('拒绝访问项目目录之外的资源文件。');
  return target;
}

function nextCopyName(existing: Set<string>, baseName: string): string {
  let index = 1;
  let candidate = `${baseName}_copy`;
  while (existing.has(candidate)) {
    index += 1;
    candidate = `${baseName}_copy_${index}`;
  }
  return candidate;
}

export async function duplicateResource(projectDir: string, resourceId: string, modId: string, newName?: string): Promise<ResourceItem> {
  const index = await readResourceIndex(projectDir);
  const sourceResource = index.resources.find(resource => resource.resourceId === resourceId);
  if (!sourceResource) throw new Error(`没有找到资源：${resourceId}`);
  const source = ensureInsideProject(projectDir, sourceResource.path);
  const baseName = path.basename(sourceResource.path, path.extname(sourceResource.path));
  const isModel = sourceResource.type === 'model';
  const modelUsage = sourceResource.usage === 'block_model' ? 'block_model' : 'item_model';
  const textureUsage = sourceResource.usage === 'block_texture' ? 'block_texture' : 'item_texture';
  const kind = isModel ? modelKind(modelUsage) : textureKind(textureUsage);
  const existingNames = new Set(index.resources
    .filter(resource => resource.type === sourceResource.type)
    .map(resource => path.basename(resource.path, path.extname(resource.path))));
  const id = validateResourceName(newName || nextCopyName(existingNames, baseName), isModel ? '模型' : '贴图');
  let dest: string;
  let generatedPath: string;
  let hash: string;
  if (isModel) {
    const data = JSON.parse(await fs.readFile(source, 'utf8'));
    dest = modelResourcePath(projectDir, modelUsage, id);
    await fs.mkdir(path.dirname(dest), { recursive: true });
    const content = `${JSON.stringify(data, null, 2)}\n`;
    await fs.writeFile(dest, content, 'utf8');
    generatedPath = modelGeneratedPath(modId, modelUsage, id);
    hash = sha256Buffer(Buffer.from(content, 'utf8'));
  } else {
    const data = await fs.readFile(source);
    validateTexturePng(data);
    dest = path.join(projectDir, 'editor/resources/textures', kind, `${id}.png`);
    await fs.mkdir(path.dirname(dest), { recursive: true });
    await fs.writeFile(dest, data);
    generatedPath = `generated/forge/src/main/resources/assets/${modId}/textures/${kind}/${id}.png`;
    hash = sha256Buffer(data);
  }
  const resource: ResourceItem = {
    ...sourceResource,
    resourceId: isModel ? modelResourceId(modelUsage, id) : `texture_${kind}_${id}`,
    path: path.relative(projectDir, dest).replace(/\\/g, '/'),
    generatedPath,
    hash,
    missing: false,
    unused: false,
    updatedAt: new Date().toISOString()
  };
  index.resources = index.resources.filter(item => item.resourceId !== resource.resourceId).concat(resource);
  await writeResourceIndex(projectDir, index);
  return resource;
}

export async function readResourceContent(projectDir: string, resourceId: string): Promise<string> {
  const index = await readResourceIndex(projectDir);
  const resource = index.resources.find(item => item.resourceId === resourceId);
  if (!resource) throw new Error(`没有找到资源：${resourceId}`);
  const target = ensureInsideProject(projectDir, resource.path);
  return fs.readFile(target, 'utf8');
}

export async function deleteResource(projectDir: string, resourceId: string): Promise<ResourceIndex> {
  const index = await readResourceIndex(projectDir);
  const resource = index.resources.find(item => item.resourceId === resourceId);
  if (!resource) return index;
  const target = ensureInsideProject(projectDir, resource.path);
  await fs.rm(target, { force: true });
  index.resources = index.resources.filter(item => item.resourceId !== resourceId);
  await writeResourceIndex(projectDir, index);
  return index;
}

export async function copyResourcesToForge(projectDir: string, modId: string): Promise<ResourceItem[]> {
  const index = await readResourceIndex(projectDir);
  const copied: ResourceItem[] = [];
  for (const resource of index.resources) {
    if (resource.type !== 'texture' && resource.type !== 'model') continue;
    const source = path.join(projectDir, resource.path);
    const isModel = resource.type === 'model';
    const textureUsage = resource.usage === 'block_texture' ? 'block_texture' : 'item_texture';
    const modelUsage = resource.usage === 'block_model' ? 'block_model' : 'item_model';
    const folder = isModel
      ? modelKind(modelUsage)
      : textureUsage === 'block_texture' ? 'block' : 'item';
    const root = isModel ? 'models' : 'textures';
    const target = path.join(projectDir, 'generated/forge/src/main/resources/assets', modId, root, folder, path.basename(resource.path));
    try {
      await fs.mkdir(path.dirname(target), { recursive: true });
      await fs.copyFile(source, target);
      resource.generatedPath = path.relative(projectDir, target).replace(/\\/g, '/');
      resource.missing = false;
      copied.push(resource);
    } catch {
      resource.missing = true;
    }
  }
  await writeResourceIndex(projectDir, index);
  return copied;
}

export async function checkResources(projectDir: string): Promise<Diagnostic[]> {
  const index = await readResourceIndex(projectDir);
  const diagnostics: Diagnostic[] = [];
  for (const resource of index.resources) {
    try {
      await fs.stat(path.join(projectDir, resource.path));
    } catch {
      diagnostics.push({
        level: 'error',
        code: 'RESOURCE_MISSING',
        message: `资源文件缺失：${resource.path}`,
        target: resource.ownerElement,
        humanAdvice: '请重新导入贴图，或把元素改为使用现有贴图。'
      });
      resource.missing = true;
    }
    if (resource.referencedBy.length === 0) {
      diagnostics.push({
        level: 'warning',
        code: 'RESOURCE_UNUSED',
        message: `资源未被使用：${resource.path}`,
        target: resource.resourceId,
        humanAdvice: '请把它绑定到元素，或从项目资源中移除。'
      });
      resource.unused = true;
    }
  }
  await writeResourceIndex(projectDir, index);
  return diagnostics;
}
