export interface ResourceItem {
  resourceId: string;
  path: string;
  generatedPath: string;
  type: 'texture' | 'model' | 'sound' | 'lang' | 'json' | 'function';
  usage: string;
  ownerElement?: string;
  referencedBy: string[];
  hash?: string;
  missing: boolean;
  unused: boolean;
  autoGenerated: boolean;
  userImported: boolean;
  advancedCodeReferenced: boolean;
  updatedAt: string;
}

export interface ResourceIndex {
  schemaVersion: string;
  resources: ResourceItem[];
}
